# Project Information
site_name: PagerDuty Postmortem Documentation
site_description: A collection of information about the PagerDuty postmortem process and industry best practices. This guide will teach you how to build a culture of continuous learning, the most important components to include in your analysis, and how to conduct effective postmortem meetings.
site_author: PagerDuty, Inc.
site_url: https://postmortems.pagerduty.com/

# Repository
repo_url: https://github.com/pagerduty/postmortem-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Postmortems'

# Set default cover image
extra:
  cover: assets/img/covers/default.png

# Contents
nav:
  - Home: 'index.md'
  - What Is a Postmortem: 'what_is.md'
  - Blameless Culture:
    - The Blameless Postmortem: 'culture/blameless.md'
    - Information Sharing: 'culture/sharing.md'
    - Accountability: 'culture/accountability.md'
  - How to Write a Postmortem:
    - Step by Step: 'how_to_write/writing.md'
    - Tips for Effective Postmortems: 'how_to_write/effective_postmortems.md'
  - The Postmortem Meeting: 'meeting.md'
  - Resources:
#    - Checklist: 'resources/checklist.md'  # TODO: Add our own checklist?
    - Analysis Questions: 'resources/analysis.md'
    - Examples: 'resources/examples.md'
    - Further Reading: 'resources/reading.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
